# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ply < Formula
  desc "Plybuild is a developer tool for automating common tasks on a spring boot project."
  homepage "https://devdimensionlab.github.io/"
  version "1.0.0-prerelease7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0-prerelease7/plybuild_1.0.0-prerelease7_darwin_arm64.tar.gz"
      sha256 "da3cbea5288ba140f07a5420aedba27abdef69780137c1f51c02430aad82b045"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0-prerelease7/plybuild_1.0.0-prerelease7_darwin_amd64.tar.gz"
      sha256 "8001cc008af9ed3e916f19cbba261d77fbefd980825b35620cbba638bc708447"

      def install
        bin.install "ply"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0-prerelease7/plybuild_1.0.0-prerelease7_linux_arm64.tar.gz"
      sha256 "4bc471b140b75aa9077911b3f8504a7c43f37b46ccc7bff576298f73233873df"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0-prerelease7/plybuild_1.0.0-prerelease7_linux_amd64.tar.gz"
      sha256 "e9d044ff384a54317e986598c7dfa5ba081db4170a5ba8f13ed815943c92de64"

      def install
        bin.install "ply"
      end
    end
  end
end
