# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plybuild < Formula
  desc "Plybuild is a developer tool for automating common tasks on a spring boot project."
  homepage "https://devdimensionlab.github.io/"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0/plybuild_1.0.0_darwin_arm64.tar.gz"
      sha256 "8581a9cd2a5239841f07ba1bcf95140406d4abea9dd9572d90a635f2af178af3"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0/plybuild_1.0.0_darwin_amd64.tar.gz"
      sha256 "83e3e34508e00b5119276969fa5c2d90816bab2a8b513d1b1e730db1515ea5c9"

      def install
        bin.install "ply"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0/plybuild_1.0.0_linux_arm64.tar.gz"
      sha256 "922b282eafc477f6ab48f44159c2ab4f2785e65e83121231b93d3f7c0d1de03f"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.0/plybuild_1.0.0_linux_amd64.tar.gz"
      sha256 "0600380d9aa3d2f4cccd711533843d56f3b76b0ff6b8fd5036e4b0c7e4c1a86d"

      def install
        bin.install "ply"
      end
    end
  end
end
