# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plybuild < Formula
  desc "Plybuild is a developer tool for automating common tasks on a spring boot project."
  homepage "https://devdimensionlab.github.io/"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.1/plybuild_1.0.1_darwin_arm64.tar.gz"
      sha256 "4c76bb3a85154b4ac8bb5864f106ebaf16bae94c7c0f9a6cf357da9a777ccd62"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.1/plybuild_1.0.1_darwin_amd64.tar.gz"
      sha256 "190cc24ae24db81da3a32bc3f3d2e9238fe3f2991dab6c5490f9449eed18e51c"

      def install
        bin.install "ply"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.1/plybuild_1.0.1_linux_arm64.tar.gz"
      sha256 "f532648cdfd613657034ee609d88b0d6861db3c18f06f61212f94e7dafced9f9"

      def install
        bin.install "ply"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/plybuild/releases/download/v1.0.1/plybuild_1.0.1_linux_amd64.tar.gz"
      sha256 "b540f49ae5b66337e6a37aa32af7cc2a7800197ee0d922aa6d62dc367c3ab348"

      def install
        bin.install "ply"
      end
    end
  end
end
